### ISSUE TITLE
Cancel button should work differently

### ISSUE THREAD

**Issue by gwutz** [spring-guides/gs-crud-with-vaadin#108]
https://github.com/spring-guides/gs-crud-with-vaadin/blob/fbca9797d4901efde7f5c08695abbaaa0325ace7/complete/src/main/java/com/example/crudwithvaadin/CustomerEditor.java#L68

Hi! I made the tutorial and I really like it. I just realized that this line might be wrong here because when I cancel the "edit" operation the Editor should hide again. Therefore it makes sense to push null into the editCustomer function right?

**Comment by Buzzardo** [comment]
To repeat what I wrote on the related PR: People may wonder what happened to the window, so I'm going to leave it as it is. This would make a good short blog post to share with the community, though.
