### ISSUE TITLE
Could not add lastname? and I think update functionality is missing?

### ISSUE THREAD

**Issue by 43v3rn88b** [spring-guides/gs-crud-with-vaadin#112]

**Comment by robertmcnees** [comment]
Hi @43v3rn88b.  I went through the guide and I was able to add a new customer with a first and last name. Can you provide more details about not being able to add lastname? Are you getting an error?

**Comment by robertmcnees** [comment]
Closing due to lack of response. If this is still an issue, please comment here and we can investigate.
