### ISSUE TITLE
the "gemfire" link leads to a 404

### ISSUE THREAD

**Issue by DominiqueComte** [spring-guides/gs-crud-with-vaadin#130]
The link [Accessing Data with GemFire](https://spring.io/guides/gs/accessing-data-gemfire/) at the bottom of the README leads to a page that does not exist.
Has it changed to "https://spring.io/guides/gs/accessing-gemfire-data-rest" maybe ?

**Comment by robertmcnees** [comment]
Thanks, @DominiqueComte. Good catch. The [Accessing Data with GemFire](https://github.com/spring-attic/gs-accessing-data-gemfire) guide was archived and moved to the spring-attic. This link should be removed from the guide.

I'll leave this open and mark this as a good issue for first time contributors. The specific line that needs removed is [here](https://github.com/spring-guides/gs-crud-with-vaadin/blob/d1d76b80619815bac958244eacdb665aa9796331/README.adoc?plain=1#L268).

**Comment by robertmcnees** [comment]
Right you are. We archived several guides recently so any cross link will be broken at this point. Looks like most of the data guides do have the gemfire link. We evaluate the guides from time to time for archival, so this will be a problem that continues to pop up.

If you see the broken links feel free to log an issue in that repository. I'll apply the `good first issue` label. I'll do the same as I come across them. I find issues like this are great for first time contributors to learn the Spring OSS contribution process. If no one grabs the issue after a while, someone on the Spring team will likely do the removal as we make other changes.

**Comment by patelherat** [comment]
Can I work on this?

**Comment by Buzzardo** [comment]
Absolutely you can work on this. I'm no longer a maintainer of the project, but I know the Spring team actively encourages community involvement. The guides are a great place to get started.
