### ISSUE TITLE
grid not working with firefox

### ISSUE THREAD

**Issue by mlappi** [spring-guides/gs-crud-with-vaadin#16]
only filter field and editor is rendered with firefox

**Comment by Legioth** [comment]
You can work around this for now by adding `setHeight("100%")` to the `MainLayout` constructor.

**Comment by mstahv** [comment]
This Vaadin regression has been fixed a while back. I think this issue should be closed.

**Comment by snicoll** [comment]
@mlappi this isn't the right place to raise issue with Vaadin.
