### ISSUE TITLE
bean validation

### ISSUE THREAD

**Issue by Nymerea** [spring-guides/gs-crud-with-vaadin#3]
Is there a easy way to get bean validation working on vaadin ?

**Comment by mstahv** [comment]
Very easy, just add a validator implementation and simple JSR 303 validators are automatically applied from your beans. [This slightly more advanced Vaadin example](https://github.com/mstahv/spring-data-vaadin-crud) uses bean validation. It also uses a add-on library called [Viritin](https://vaadin.com/directory#!addon/viritin) to support bean level validators (~ cross field validators) and validation on the fly when user is inputting the data.

Adding validation example to next version of this tutorial is a good idea.

**Comment by Nymerea** [comment]
I didn't know about Viritin addon ! Thanks for the sharing :-)

**Comment by gregturn** [comment]
I'm going to go ahead and close this issue, since we don't plan on turning this guide into an extensive tutorial. Feel free to keep discussing deatils.
