### ISSUE TITLE
Unable to determine mode of operation

### ISSUE THREAD

**Issue by upost** [spring-guides/gs-crud-with-vaadin#42]
Hi,
the guide doesn't state how to start the project.
I tried:
mvn spring-boot:run (inside the complete directory)
build is successful, but opening localhost:8080 yields the Whitelabel Error Page with this information:

```
There was an unexpected error (type=Internal Server Error, status=500).
Unable to determine mode of operation. To use npm mode, ensure 'flow-build-info.json' exists on the classpath. With Maven, this is handled by the 'prepare-frontend' goal. To use compatibility mode, add the 'flow-server-compatibility-mode' dependency. If using Vaadin with Spring Boot, instead set the property 'vaadin.compatibilityMode' to 'true' in 'application.properties'.
```

What am I missing?

**Comment by snicoll** [comment]
@upost thanks for reporting it.

@mstahv this looks like something that's required as part of a Vaadin upgrade. If that's a decision the user has to make, I think we should also upgrade the guide itself to mention it. Thoughts?

**Comment by mstahv** [comment]
There is a regression that makes Vaadin app not to start without haven a vaadin-maven-plugin and  prepare-frontend goal configured. The fix should be on it's way, hopefully soon. In the mean time, if you downgrade to 13.0.13, everything should work.
