### ISSUE TITLE
No mention of Spring Initializer on spring.io/guides

### ISSUE THREAD

**Issue by NgyAnthony** [spring-guides/gs-crud-with-vaadin#53]
Hi, did you omit mentioning Spring Initializer on the official guide of the website on purpose or is it just a mistake ? 
https://spring.io/guides/gs/crud-with-vaadin/

Also the guide mentions "Accessing data with JPA" but the link is dead. https://spring.io/gs/accessing-data-jpa

**Comment by gregturn** [comment]
The guides were actually created before start.spring.io. Not this guide, but the concept in general.

@Buzzardo, though, has undertaken porting them to its usage, so it's on a best-effort basis that such changes are happening.

**Comment by NgyAnthony** [comment]
> The guides were actually created before start.spring.io. Not this guide, but the concept in general.
> 
> @Buzzardo, though, has undertaken porting them to its usage, so it's on a best-effort basis that such changes are happening.

I see ! Thank you for answering so quickly. Those guides are very well made, so I'm not really complaining. 👍 

I'll let you guys decide if you want to close this issue or not.

**Comment by Buzzardo** [comment]
We appear to have a caching problem. The version on master includes a "Starting with Spring Initializr" section. We're looking into it.

The link you mentioned is broken in both versions. I'll fix that once we have the caching issue sorted.

Thanks much for letting us know, @NgyAnthony.

**Comment by Buzzardo** [comment]
Fixed now. @gregturn figured out that we had HTTP when we needed HTTPS, so our cache wasn't resetting. I fixed the broken link.
