### ISSUE TITLE
Cannot incorporate into pom.xml

### ISSUE THREAD

**Issue by Panthera-onca** [spring-guides/gs-crud-with-vaadin#79]
Neither spring initialiser nor direct incorporation into pom.xml in accordance with your example get the module working properly. Is this because I am using Eclipse and not IntelliJ, or is there some other reason?

**Comment by Panthera-onca** [comment]
![image](https://user-images.githubusercontent.com/43185693/112733321-a3dfd900-8f3f-11eb-8c8b-ba70443595e1.png)

**Comment by Panthera-onca** [comment]
Tell me, please, if I am doing something wrong.

**Comment by Buzzardo** [comment]
It shouldn't matter whether you use IntelliJ or Eclipse. For my testing, I use neither and run the test script in the `test` directory.

**Comment by Panthera-onca** [comment]
My bad, I failed to specify version  14.0.0 in dependency management, now it works like a charm, sorry
