### ISSUE TITLE
Requires node and npm to be installed

### ISSUE THREAD

**Issue by wlfbck** [spring-guides/gs-crud-with-vaadin#96]
Title, basically. Just downloaded the complete example and tried to run it. You will get an error from Vaadin (which is a bug in Vaadin; it should be installing it itself, but doesn't). This can be solved by manually installing node and npm, but should be mentioned in the guide.

**Comment by mstahv** [comment]
@wlfbck Did you file a bug to Vaadin repository? Because auto-installation of node should work. The version used but the tutorial was bit outdated, but it shouldn't matter in this case.

**Comment by wlfbck** [comment]
Yeah i reported it to them: https://github.com/vaadin/flow/issues/11056#issuecomment-967177115

That issue has been there for a while. I'm surprised not more people have run into it.

**Comment by mstahv** [comment]
👍 The best thing about the latest version is that Node/npm isn't needed at all anymore, not even as autoinstalled 😎
